/**
 * PSGC API
 * Current data is as of June 30, 2021. Data is based from https://psa.gov.ph/classification/psgc/ (Publication file).<br/><br/>Limitation: The content-type header of the API is text/html instead of application/json. Use API JSON call if content-type header application/json is needed<br/><br/>Issues/request/suggestions: Kindly file your concern here <a href='https://gitlab.com/psgc/api/issues' target='_blank'>https://gitlab.com/psgc/api/issues</a>
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SubMunicipality { 
    code?: string;
    name?: string;
    oldName?: string;
    districtCode?: string | boolean;
    provinceCode?: string | boolean;
    regionCode?: string;
    islandGroupCode?: string;
}